# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e30c396159bf5b786c82b2988cd0d86214e8be953702cc1f3847dd68b0c13cae50e751347b3dec45eea49514b39c8813570f0295b6a5a3dcef913187d54c520f

test:
  secret_key_base: b95387a3aca91543282a58d218900ac497466f19e568272400aa8d59d988d5bb4f5ca6a3e318839442a28ae94c0107ad24a41155ad138e2f11eb5c64e303aaa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
